openapi: 3.0.1
info:
  title: User API
  description: API for managing users.
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get info for all users in connected databases
      operationId: getUsers
      parameters:
        - in: query
          name: filter
          description: 'Aggregate object to hold possible query params'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSearchFilter'
      responses:
        '200':
          description: A list of user data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserData'
      tags:
        - User
components:
  schemas:
    UserData:
      type: object
      properties:
        id:
          type: string
          description: User ID
        username:
          type: string
          description: Username
        name:
          type: string
          description: User's first name
        surname:
          type: string
          description: User's last name
    UserSearchFilter:
      type: object
      properties:
        id:
          type: string
          description: User ID
        username:
          type: string
          description: Username
        name:
          type: string
          description: User's first name
        surname:
          type: string
          description: User's last name
