spring:
  application:
    name: comparus-testTask
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: none
springdoc:
  api-docs:
    path: /api-docs
data-sources:
  - name: data-base-1
    strategy: postgres #this property is optional, only if you implements multiple database type support (Postgres, ORACLE, MySQL...)
    url: jdbc:postgresql://localhost:5432/users_db
    table: users
    user: testuser
    password: testpass
    mapping:
      id: user_id
      username: login
      name: first_name
      surname: last_name
  - name: data-base-2
    strategy: postgres
    url: jdbc:postgresql://localhost:5433/users_ldap_db
    table: user_table
    user: testuser
    password: testpass
    mapping:
      id: ldap_login
      username: ldap_login
      name: name
      surname: surname
  - name: data-base-3
    strategy: mysql
    url: jdbc:mysql://localhost:3306/db
    table: mysql_users
    user: testuser
    password: testpass
    mapping:
      id: id
      username: username
      name: first_name
      surname: last_name